# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# workaround to get 3.7 to work:
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox-travis

# command to run tests, e.g. python setup.py test
script:
  tox
